apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.deploymentName }}
  name: {{ .Values.deploymentName }}
  {{- else }}
  name: {{ .Release.Name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name }}
    version: {{ .Release.name }}
    component: {{ .Values.component }}
    tag: {{ .Values.tag }}
    circleId: {{ .Values.circleId }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      version: {{ .Release.Name }}
      component: {{ .Values.component }}
      tag: {{ .Values.tag }}
      circleId: {{ .Values.circleId }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: '{{ .Values.sidecarIstio.enabled }}'
      labels:
        app: {{ .Values.service.name }}
        version: {{ .Release.Name }}
        component: {{ .Values.component }}
        tag: {{ .Values.tag }}
        circleId: {{ .Values.circleId }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.image.tag }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{ range $i, $var := .Values.envVars -}}
          - name: {{ $var.name | upper}}
            value: {{ $var.value | quote}}
          {{ end }}
          {{ range $i, $var := .Values.secretEnvVars -}}
          - name: {{ $var.name | upper }}
            valueFrom:
              secretKeyRef:
                name: {{ $var.secretName }}
                key: {{ $var.secretKey }}
          {{ end }}
          resources:
  {{ toYaml .Values.resources | indent 12 }}
imagePullSecrets:
  - name: realwavelab-registry
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}