version: '3'

services:
  database:
    image: postgres:9.6-alpine
    container_name: postgresql-event-manager
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=event-manager
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - MAX_CONNECTIONS=300
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
    postgres-data:
      driver: local

networks:
  app-network:
    driver: bridge