apiVersion: v2
name: office-hours-service
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: 10.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled